<?php
/**
 * Copyright (c) Devis
 */

/** @var $block \Devis\Quotation\Block\Cart\AddToQuotation */
?>
<?php if ($block->isQuotationEnabled()) :?>
    <button type="button"
            title="<?= $block->escapeHtmlAttr(__('Get Quotation')) ?>"
            data-mage-init='{"Devis_Quotation/js/quotation": {"config": "element"}}'
            class="action primary quotation"
            id="product-addtoquote-button-checkout">
        <span><?= $block->escapeHtml(__('Get Quotation')) ?></span>
    </button>
<?php endif ?>
