<?php
/**
 * Copyright (c) Davis
 */

/** @var $block \Devis\Quotation\Block\Product\View\AddToQuotation */
?>
<?php if ($block->isQuotationEnabled()) :?>
<div class="actions">
    <button type="button"
            title="<?= __('Get Quotation') ?>"
            class="action primary tocart"
            data-mage-init='{"Devis_Quotation/js/quotation": {"config": "element"}}'
            id="product-addtoquote-button" disabled>
        <span><?= __('Get Quotation') ?></span>
    </button>
</div>
<?php endif; ?>
